### ISSUE TITLE
[Request] Please add support for AMO and Google Image

### ISSUE THREAD

**Issue by FatOrangutan** [nokeya/direct-links-out#1]
I just discovered your script over on OpenUserJS. Thanks for making this, as it quickly replaced some 3-4 scripts I was using for various websites.
Could you add support for [AMO](https://addons.mozilla.org/en-US/firefox/)? Here is a test page: [link](https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/). If you scroll down a bit, you'd see a 'Support site' link. Any of the other external links in the page, for e.g. those in 'About this Add-on' have redirection pages too.
BTW, you could consider putting up your script on [GreasyFork](https://greasyfork.org/en) too, for improved visibility.
Thanks.
Edit: Although the script works very well on Google, it fails to prevent redirection on a Google Image Search. You can reproduce this by doing an image search (or use this [link](https://www.google.com/search?q=why&tbm=isch)), then clicking on any of the images for the 'Visit page' and 'View image' links to show up. Now if you click either of them, you'd go through Google's redirection. Alternatively, just right click either of these for the Google redirect URL to reveal itself.
Would be great if you could fix this. Thanks.

**Comment by nokeya** [comment]
Published the script on the greasyfork. Thank you!
Solutions for google images and AMO are in process

**Comment by nokeya** [comment]
Done. 
AMO redirects are being removed after some delay (100ms) - it must be sufficient I think.

**Comment by FatOrangutan** [comment]
Thank you! It works pretty well for both Google Images and AMO now.
