### ISSUE TITLE
Поддержка wikimapia.org

### ISSUE THREAD

**Issue by Juggernaut99** [nokeya/direct-links-out#11]
Спасибо за отличный скрипт!
Добавьте поддержку внешних ссылок на wikimapia.org типа http://wikimapia.org/external_link?url=
[Пример](http://wikimapia.org/external_link?url=http://vylazki.ru/item/galkinskoe-boloto) вот [тут](http://wikimapia.org/#lang=ru&lat=54.743650&lon=35.775261&z=12&m=b&show=/11818027/ru/%D0%93%D0%B0%D0%BB%D0%BA%D0%B8%D0%BD%D1%81%D0%BA%D0%BE%D0%B5-%D0%B1%D0%BE%D0%BB%D0%BE%D1%82%D0%BE)

**Comment by vad1m** [comment]
Fixed it #16
