### ISSUE TITLE
[PENDING] Редиректы на mozilla.org

### ISSUE THREAD

**Issue by sergeevabc** [nokeya/direct-links-out#13]
Смотрю, к вам [уже обращались][1] с этой темой, но исправлений пока нет. Открываем страничку какого-нибудь расширения (например, [PrivateTab][2]), следуем курсором направо вниз до ссылки на «сайт поддержки» — она содержит редирект, начинающийся с outgoing.prod.mozaws.net. 

[1]: https://greasyfork.org/en/forum/discussion/12491/mozilla-org-to-fix
[2]: https://addons.mozilla.org/en-US/firefox/addon/private-tab/

**Comment by sergeevabc** [comment]
Ау! Есть кто живой?

**Comment by sergeevabc** [comment]
Ау! Есть кто живой?

**Comment by vad1m** [comment]
Fixed, waiting for merge #15
