### ISSUE TITLE
Breaks some links on vk.com

### ISSUE THREAD

**Issue by hant05080** [nokeya/direct-links-out#23]
Версия скрипта: 2.18
Браузер: Mozilla Firefox 53.0, Debian GNU/Linux

Скрипт ломает некторые ссылки ВК, добавляя к ним лишние символы:

- ссылки, указанные как "Веб-сайт" на личных страницах:  `&cc_key=`;
- сыылки, отправленные в личных сообщениях: `&cc_key=`;
- ссылки, прикреплённые в личных сообщениях: `&el=snippet` при клике на название сайта или редирект через `away.vk.com` при клике на миниатюру.

**Comment by nokeya** [comment]
Исправлено. Если еще где в вк вылезет - открывайте этот тикет снова
