### ISSUE TITLE
[Request | NSFW] Gelbooru

### ISSUE THREAD

**Issue by kowith337** [nokeya/direct-links-out#24]
Due to recent changes that they replace all thumbnail links (aka. post lists) as redirected link.
See example in
- [`view-source`](https://cloud.githubusercontent.com/assets/16535467/25803762/ad19ac20-3422-11e7-885a-e10c010f5a63.png)
- [Side-by-side with DevTools](https://cloud.githubusercontent.com/assets/16535467/25946602/14d363f6-3676-11e7-9159-80a6ff66c46e.png)

**Example of the direct link that should be...**
`https://gelbooru.com/index.php?page=post&s=view&id=1234567`

**Expect for this work**
- Find `PostID` from
  - `span id="s1234567"` OR
  - `a id="p1234567"`
- Replace old redirected links by get number from those value above (remember to remove `s` or `p` at number header
- Results is `https://gelbooru.com/index.php?page=post&s=view&id=<PostID>`

**Comment by nokeya** [comment]
Purpose of this script is to rewrite links going **out** from the site, not for redirects within the site.
I can code and publish separate script dedicated for this gelbooru issue, how do you like this idea?

**Comment by kowith337** [comment]
Yes, but sorry at first place because I've troubled you due to request the fix that not related to this work.
