### ISSUE TITLE
[Bug] Переход по ссылкам из постов ВК.

### ISSUE THREAD

**Issue by fixator10** [nokeya/direct-links-out#3]
При переходе по ссылке из поста ВК в конце остается %26post%3D-*Idпоста*

Пример:
![2016-01-22 15-44-45](https://cloud.githubusercontent.com/assets/11073934/12509878/3daaa3b6-c11f-11e5-9e4e-02cee02c17e6.png)

**Comment by nokeya** [comment]
FF43, Chromium 47 - все как надо. Браузер?

**Comment by fixator10** [comment]
Google Chrome 47.0.2526.111 m

**Comment by nokeya** [comment]
Все должно быть ОК. Скорее всего конфликтует с другими скриптами/аддонами для вк.

**Comment by fixator10** [comment]
Проверил. Проблема возникает только в URL формата "http://google.com", С URL формата "http://google.com/" или "http://google.com/?parameters" такого не происходит.

![2016-01-23 09-28-40](https://cloud.githubusercontent.com/assets/11073934/12528567/0ad4ae6a-c1b4-11e5-891d-57af3ff3f3af.png)
![2016-01-23 09-29-17](https://cloud.githubusercontent.com/assets/11073934/12528568/0af49f90-c1b4-11e5-8534-abd9838011d7.png)
![2016-01-23 09-30-31](https://cloud.githubusercontent.com/assets/11073934/12528569/0b0373da-c1b4-11e5-907c-3d380f82252e.png)

**Comment by nokeya** [comment]
Исправлено
