### ISSUE TITLE
В Google не работает

### ISSUE THREAD

**Issue by led9** [nokeya/direct-links-out#4]
Приветствую,
В гугле копируется их длинная ссылка с редиректом.

В гугле работает вот это расширение - убирает редиректы:
https://chrome.google.com/webstore/detail/undirect/dohbiijnjeiejifbgfdhfknogknkglio
Исходный код = https://github.com/xwipeoutx/undirect

Исправьте, пожалуйста.

**Comment by nokeya** [comment]
Действительно, окей, поправлю в течение пары дней.

**Comment by nokeya** [comment]
Как выяснилось - это проблема Violent Monkey, скрипт просто не активируется для гугла, хотя шаблоны прописаны вроде правильно.
Написал автору - https://github.com/Violentmonkey/violentmonkey/issues/42 - посмотрим что ответит.

Временное решение - добавить гугл вручную в пользовательские мета-данные, скрипт заработает.

**Comment by led9** [comment]
Автор Violent Monkey поправил своё расширение - 2.2.6, теперь ваш скрипт работает.
(в магазине расширений Opera ещё не обновлено, но можно поставить обновлённое из магазина гугла).
Спасибо за быстрое пинание Violent Monkey :)
