### ISSUE TITLE
Getting 'TypeError: node.getElementsByTagName is not a function' errors

### ISSUE THREAD

**Issue by FatOrangutan** [nokeya/direct-links-out#8]
Hello,

There are some 'TypeError: node.getElementsByTagName is not a function' errors in my Browser Console, arising from this script.

![](http://i.imgur.com/hMCuOc1.png)

I'm on Firefox 50.0a2 (2016-09-01), Greasemonkey 3.9 and Direct Links Out 2.15.

Please look into this. Thanks.

**Comment by nokeya** [comment]
Hello!
Can you please tell me domain(s) where you getting these errors?

2016-09-02 14:30 GMT+03:00 FatOrangutan <notifications@github.com>:

**Comment by FatOrangutan** [comment]
I'm getting it for instance on the following pages: https://www.google.com/#q=test and https://addons.mozilla.org/en-US/firefox/.

Are you not getting any errors on your end? I have e10s disabled, if that makes a difference.

**Comment by nokeya** [comment]
I cant test it right now, will test and fix next weekend

2016-09-03 3:20 GMT+03:00 FatOrangutan <notifications@github.com>:

**Comment by nokeya** [comment]
Was unable to reproduce on Firefox 43, 45, 48 and 51 (Nightly).
But will add some guard code, to prevent these messages and undefined behaviour.
